apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-provisioning-manager
  labels:
    app: cpm
    version: v1
    tier: backend
    owner: ezio-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpm
  template:
    metadata:
      labels:
        app: cpm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: cpm-container
          image: eziolima/cloud-provisioning-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: cpm-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cpm-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cpm-secrets
                  key: DB_PASSWORD
            - name: SPRING_LDAP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cpm-secrets
                  key: LDAP_USERNAME
            - name: SPRING_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cpm-secrets
                  key: LDAP_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5