apiVersion: v1
kind: Service
metadata:
  name: cloud-provisioning-manager-service
spec:
  type: LoadBalancer
  selector:
    app: cpm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080